### ISSUE TITLE
Introduce new modification type "updated"

### ISSUE THREAD

**Issue by alrik** [release-notes/release-notes-spec#7]
The new **updated** modification type targets dependency updates or text patches.

example

```yaml
title: Example of new **updated**
releases:
- version: Next
  updated:
  - Upgrade to `another-dep@1.2.0` from `v1.1.0`
  - Update COPYRIGHT year to 2017.
  - Add `@someone` to list of contributors.
```
