### ISSUE TITLE
Introduce new change set type: documentation

### ISSUE THREAD

**Issue by alrik** [release-notes/release-notes-spec#8]
Documentation is an essential part of good software, thus it deserves an own area within a release statement.

I see 3 options for naming the new modification type:
* docs
* documentation
* or both with docs being alias of documentation

I like `docs` best. It is short and commonly used. `documentation` sound more official but is a quite long word. Having both options will bloat up the spec without much use.

**Acceptance Criteria**
* [ ] Add specification of new modification type for labeling documentation changes

**Comment by alrik** [comment]
@derlarsen @baranga @IjzerenHein do you have any feedback on this?

**Comment by baranga** [comment]
@alrik Could you provide a example of usage?

**Comment by alrik** [comment]
I'd use it for statements like these:

```yml
title: Release Notes of an awesome project
releases:
- version: Unreleased
  added:
  - Add some fancy feature.
  docs:
  - Add an [example](examples/fancy-feature/) on how to use fancy feature.
  - Fixed api status code description of some legacy feature.
  - Setup code of conduct and introduce getting started tutorial.
  - Update license year in all code doc block annotations.
```
